"use client"

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { TrendingUp, Shield, Zap, Globe, ChevronRight, LineChart, Activity, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { WhatsAppButton } from '@/components/WhatsAppButton';
import { AdminPanel } from '@/components/AdminPanel';
import { useUser } from '@/firebase';

export default function HomePage() {
  const router = useRouter();
  const { user } = useUser();
  const [logoClicks, setLogoClicks] = useState(0);
  const [isAdminOpen, setIsAdminOpen] = useState(false);

  useEffect(() => {
    if (user && !isAdminOpen) {
      router.push('/dashboard');
    }
  }, [user, router, isAdminOpen]);

  const handleLogoClick = () => {
    const nextClicks = logoClicks + 1;
    if (nextClicks >= 7) {
      setIsAdminOpen(true);
      setLogoClicks(0);
    } else {
      setLogoClicks(nextClicks);
    }
  };

  const features = [
    {
      icon: <Zap className="h-5 w-5 sm:h-6 sm:w-6 text-accent" />,
      title: "Real-time AI Signals",
      desc: "Institutional grade signals generated by custom models. 7 Free signals for every member."
    },
    {
      icon: <TrendingUp className="h-5 w-5 sm:h-6 sm:w-6 text-primary" />,
      title: "Forex & Crypto",
      desc: "Comprehensive coverage from major currency pairs to leading cryptocurrencies."
    },
    {
      icon: <Shield className="h-5 w-5 sm:h-6 sm:w-6 text-accent" />,
      title: "Risk Management",
      desc: "Every signal includes precise Entry, Take Profit, and Stop Loss levels."
    },
    {
      icon: <Globe className="h-5 w-5 sm:h-6 sm:w-6 text-primary" />,
      title: "Market Insights",
      desc: "Integrated TradingView widgets provide a holistic view of global markets."
    }
  ];

  return (
    <div className="min-h-screen bg-[#050505] flex flex-col overflow-x-hidden">
      <div className="fixed top-[44px] w-full z-50 px-2 sm:px-4 mt-2">
        <div className="border-b border-white/5 bg-black/40 backdrop-blur-xl glassmorphism rounded-xl sm:rounded-2xl">
          <header className="container mx-auto h-14 sm:h-16 flex items-center justify-between px-3 sm:px-6">
            <div 
              onClick={handleLogoClick}
              className="text-lg sm:text-xl font-black font-headline cursor-pointer select-none tracking-tighter flex items-center gap-2 group"
            >
              <div className="w-8 h-8 sm:w-10 sm:h-10 bg-primary/10 border border-primary/30 rounded-lg sm:rounded-xl flex items-center justify-center group-hover:shadow-[0_0_20px_rgba(59,130,246,0.4)] transition-all">
                <LineChart className="h-5 w-5 sm:h-6 sm:w-6 text-primary" />
              </div>
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400 font-bold hidden xs:block">
                DEEBDATA <span className="text-primary">TRADING</span>
              </span>
              <span className="text-primary font-black block xs:hidden">DDT</span>
            </div>
            <nav className="hidden lg:flex items-center gap-8 text-sm font-medium text-muted-foreground">
              <Link href="/" className="text-white hover:text-primary transition-colors">Home</Link>
              <Link href="/dashboard" className="hover:text-primary transition-colors">Signals</Link>
            </nav>
            <div className="flex items-center gap-2 sm:gap-4">
              <Link href="/login">
                <Button variant="ghost" size="sm" className="text-white hover:text-primary text-xs sm:text-sm font-bold">Sign In</Button>
              </Link>
              <Link href="/login">
                <Button size="sm" className="bg-primary text-white font-black px-4 sm:px-6 glow-primary hover:scale-105 transition-all text-xs sm:text-sm">
                  Join Now
                </Button>
              </Link>
            </div>
          </header>
        </div>
      </div>

      <main className="flex-grow pt-32 sm:pt-48">
        <section className="container mx-auto px-4 sm:px-6 py-10 sm:py-20 text-center relative">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[300px] sm:w-[800px] h-[200px] sm:h-[400px] bg-primary/5 rounded-full blur-[80px] sm:blur-[120px] pointer-events-none" />
          
          <div className="inline-flex items-center gap-2 bg-secondary/50 border border-white/10 px-3 py-1 rounded-full text-[10px] sm:text-xs font-bold uppercase tracking-widest text-primary mb-6 sm:mb-8 relative z-10">
            <Activity className="h-3 w-3 animate-pulse text-accent" /> Institutional Grade Analytics
          </div>
          
          <h1 className="text-3xl sm:text-6xl md:text-8xl font-black font-headline leading-[1.2] sm:leading-[1.1] max-w-5xl mx-auto mb-6 sm:mb-8 tracking-tighter relative z-10">
            Professional <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-accent to-primary bg-[length:200%_auto] animate-gradient">
              AI-Powered
            </span> <br />
            Trading Signals
          </h1>
          
          <p className="text-sm sm:text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-8 sm:mb-12 leading-relaxed font-medium relative z-10 px-4">
            Pay once to unlock global markets with high-precision entries and real-time AI insights. 7 Free signals for all members.
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 sm:gap-6 relative z-10 px-4">
            <Link href="/login" className="w-full sm:w-auto">
              <Button className="w-full sm:w-auto h-12 sm:h-16 px-8 sm:px-12 text-base sm:text-lg font-black bg-primary text-white animate-pulse-glow hover:scale-105 transition-all rounded-xl">
                Get Started Now <ArrowRight className="ml-2 h-4 w-4 sm:h-5 sm:w-5" />
              </Button>
            </Link>
            <Link href="/login" className="w-full sm:w-auto">
              <Button variant="outline" className="w-full sm:w-auto h-12 sm:h-16 px-8 sm:px-12 text-base sm:text-lg font-black border-white/10 text-white hover:bg-white/5 transition-all rounded-xl glassmorphism">
                VIP Plans - $25/Mo
              </Button>
            </Link>
          </div>
        </section>

        <section className="container mx-auto px-4 sm:px-6 py-16 sm:py-32 border-t border-white/5">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-8">
            {features.map((f, i) => (
              <div key={i} className="group p-6 sm:p-10 rounded-2xl sm:rounded-3xl bg-[#121212]/50 border border-white/5 hover:border-primary/30 transition-all duration-500 glassmorphism">
                <div className="w-10 h-10 sm:w-14 h-14 rounded-xl sm:rounded-2xl bg-black border border-white/10 flex items-center justify-center mb-6 sm:mb-8 group-hover:scale-110 group-hover:border-primary/50 transition-all">
                  {f.icon}
                </div>
                <h3 className="text-lg sm:text-xl font-bold font-headline mb-3 sm:mb-4 tracking-tight">{f.title}</h3>
                <p className="text-muted-foreground text-xs sm:text-sm leading-relaxed font-medium">{f.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="bg-black/40 py-16 sm:py-32 border-y border-white/5 glassmorphism relative overflow-hidden">
          <div className="absolute inset-0 bg-primary/5 opacity-30 pointer-events-none" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10">
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 sm:gap-16 text-center">
              <div>
                <div className="text-3xl sm:text-5xl md:text-6xl font-black font-headline text-accent mb-2 sm:mb-3 tracking-tighter">92.4%</div>
                <div className="text-[8px] sm:text-[10px] uppercase tracking-[0.2em] sm:tracking-[0.3em] text-muted-foreground font-black">Historical Accuracy</div>
              </div>
              <div>
                <div className="text-3xl sm:text-5xl md:text-6xl font-black font-headline text-white mb-2 sm:mb-3 tracking-tighter">24/7</div>
                <div className="text-[8px] sm:text-[10px] uppercase tracking-[0.2em] sm:tracking-[0.3em] text-muted-foreground font-black">Market Monitoring</div>
              </div>
              <div>
                <div className="text-3xl sm:text-5xl md:text-6xl font-black font-headline text-primary mb-2 sm:mb-3 tracking-tighter">15k+</div>
                <div className="text-[8px] sm:text-[10px] uppercase tracking-[0.2em] sm:tracking-[0.3em] text-muted-foreground font-black">Elite Members</div>
              </div>
              <div>
                <div className="text-3xl sm:text-5xl md:text-6xl font-black font-headline text-accent mb-2 sm:mb-3 tracking-tighter">$2B+</div>
                <div className="text-[8px] sm:text-[10px] uppercase tracking-[0.2em] sm:tracking-[0.3em] text-muted-foreground font-black">Volume Analyzed</div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer className="bg-[#050505] border-t border-white/5 py-12 sm:py-20 relative overflow-hidden">
        <div className="container mx-auto px-4 sm:px-6 text-center">
          <div className="text-xl sm:text-2xl font-black font-headline tracking-tighter mb-6 flex items-center justify-center gap-2">
            <LineChart className="h-6 w-6 sm:h-7 sm:w-7 text-primary" />
            DEEBDATA <span className="text-primary">TRADING</span>
          </div>
          <p className="text-muted-foreground text-xs sm:text-sm max-w-xl mx-auto mb-8 sm:mb-10 font-medium leading-relaxed px-4">
            Trading involves significant risk. Our AI signals are analytical tools for professional assistance. Pay to unlock full access.
          </p>
          <div className="flex flex-wrap justify-center gap-4 sm:gap-10 text-[9px] sm:text-xs text-muted-foreground font-black uppercase tracking-widest mb-10 sm:mb-12 px-4">
            <Link href="#" className="hover:text-primary transition-colors">Terms</Link>
            <Link href="#" className="hover:text-primary transition-colors">Privacy</Link>
            <Link href="#" className="hover:text-primary transition-colors">Risk Disclosure</Link>
          </div>
          <div className="space-y-3">
            <div className="text-[9px] sm:text-xs text-muted-foreground/40 font-bold uppercase tracking-[0.3em] sm:tracking-[0.4em]">
              Powered by Hassan Deeb
            </div>
            <div className="text-[8px] sm:text-[11px] text-muted-foreground/20 font-black uppercase tracking-[0.4em] sm:tracking-[0.6em]">
              © 2026 DeebData Trading Platform.
            </div>
          </div>
        </div>
      </footer>

      <WhatsAppButton />
      <AdminPanel isOpen={isAdminOpen} onClose={() => setIsAdminOpen(false)} />
      
      <style jsx global>{`
        @keyframes gradient {
          0% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
          100% { background-position: 0% 50%; }
        }
        .animate-gradient {
          background-size: 200% auto;
          animation: gradient 4s linear infinite;
        }
      `}</style>
    </div>
  );
}